### ISSUE TITLE
"maximum" fan speed don't work :-(

### ISSUE THREAD

**Issue by MBrubru** [laszlojakab/homeassistant-easycontrols#103]
Hi,
First of all, a huge thank you for this integration :-)
I want to go to maximum speed (4) using automation.
Here is the code snippet I use:
```
service: easycontrols.start_party_mode
data:
    entity_id: fan.vmc
    speed: maximun
    duration: 1000
```

and the error that the system returns to me:
"_Stopped because an error was encountered at ...
'**maximum**' is not in list_"
Is this a bug, or am I making a mistake?
Thanks
Mark
PS: when I do the same thing to switch to speed 1=basic, 2=rated or 3=intensive it works
